---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system

spec:
  externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: websecure
      port: 443
    - protocol: TCP
      name: admin
      port: 8080
  selector:
    app: traefik
  type: LoadBalancer
